### ISSUE TITLE
Database schema design

### ISSUE THREAD

**Issue by MissDine** [Amaris-Digital/blog-upskill#2]
## Create relationships
- User
- Post
- Categories
- Tags
- Comments

**Comment by Muriithi-Gitonga** [comment]
Here is the [*link*](https://drawsql.app/teams/david-37/diagrams/blog)  to our database schema diagram  @otsembo

**Comment by MissDine** [comment]
Here is the [figma](https://www.figma.com/file/xBKRX63cYM6FVlmSgtZ4K0/Untitled?node-id=0-1&t=rkXJMBOlxoWfnLbM-0)link to our blog site @otsembo
